import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import 'package:aura_app/data/models/product.dart';
import 'package:aura_app/data/models/banner_category.dart';

final kProducts = <Product>[
  // ── Men's Formal ──────────────────────────────────────────
  const Product(
    id: 'p01',
    name: 'Slim Oxford Shirt',
    brand: 'Ralph Lauren',
    description:
        'A timeless oxford shirt in premium 100% cotton. Button-down collar, slim fit, subtle texture. Pairs perfectly with chinos or tailored trousers for a smart-casual look.',
    price: 23997.0,
    originalPrice: 36000.0,
    category: 'Men',
    subCategory: 'Formal',
    images: [
      'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=700&q=85',
      'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=700&q=85',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['White', 'Light Blue', 'Navy'],
    rating: 4.7,
    reviewCount: 324,
    soldCount: 890,
    isFeatured: true,
    rackId: 'rack_men_formal',
    rackName: "Men's Formal",
    details: {
      'Material': '100% Cotton',
      'Fit': 'Slim Fit',
      'Care': 'Machine Wash',
      'Origin': 'Portugal'
    },
  ),
  const Product(
    id: 'p02',
    name: 'Wool Blazer',
    brand: 'Tommy Hilfiger',
    description:
        'Sophisticated wool-blend blazer with single-button closure, notch lapels, and structured shoulders for a sharp professional appearance.',
    price: 74997.0,
    originalPrice: 114000.0,
    category: 'Men',
    subCategory: 'Formal',
    images: [
      'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=700&q=85',
      'https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?w=700&q=85',
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Charcoal', 'Navy', 'Black'],
    rating: 4.9,
    reviewCount: 187,
    soldCount: 420,
    isFeatured: true,
    rackId: 'rack_men_formal',
    rackName: "Men's Formal",
    details: {
      'Material': '70% Wool, 30% Poly',
      'Fit': 'Slim Fit',
      'Care': 'Dry Clean Only',
      'Lining': 'Full'
    },
  ),
  const Product(
    id: 'p03',
    name: 'Tailored Dress Trousers',
    brand: 'Dior',
    description:
        'Impeccably cut dress trousers in a premium wool-stretch blend. Flat front, slim silhouette. The backbone of any formal wardrobe.',
    price: 41997.0,
    originalPrice: 58500.0,
    category: 'Men',
    subCategory: 'Formal',
    images: [
      'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=700&q=85',
      'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=700&q=85',
    ],
    sizes: ['28', '30', '32', '34', '36'],
    colors: ['Black', 'Charcoal', 'Navy'],
    rating: 4.6,
    reviewCount: 211,
    soldCount: 580,
    isNew: true,
    rackId: 'rack_men_formal',
    rackName: "Men's Formal",
    details: {
      'Material': '95% Wool, 5% Elastane',
      'Fit': 'Slim',
      'Rise': 'Mid',
      'Care': 'Dry Clean'
    },
  ),
  // ── Men's Casual ──────────────────────────────────────────
  const Product(
    id: 'p04',
    name: 'Slim Chino',
    brand: 'Polo Ralph Lauren',
    description:
        'Versatile chino in lightweight cotton-stretch. Moves with you through the workday and beyond. Available in classic seasonal colors.',
    price: 26997.0,
    category: 'Men',
    subCategory: 'Casual',
    images: [
      'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=700&q=85',
      'https://images.unsplash.com/photo-1542272604-787c3835535d?w=700&q=85',
    ],
    sizes: ['28', '30', '32', '34', '36'],
    colors: ['Khaki', 'Navy', 'Olive', 'Stone'],
    rating: 4.5,
    reviewCount: 458,
    soldCount: 1200,
    isNew: true,
    rackId: 'rack_men_casual',
    rackName: "Men's Casual",
    details: {
      'Material': '97% Cotton, 3% Elastane',
      'Fit': 'Slim',
      'Rise': 'Mid',
      'Care': 'Machine Wash'
    },
  ),
  const Product(
    id: 'p05',
    name: 'Cable Knit Sweater',
    brand: 'Gucci',
    description:
        'Timeless cable-knit sweater in 100% merino wool. Dropped shoulders, ribbed cuffs and hem deliver an elevated cold-weather layer you will reach for season after season.',
    price: 35997.0,
    originalPrice: 49500.0,
    category: 'Men',
    subCategory: 'Casual',
    images: [
      'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=700&q=85',
      'https://images.unsplash.com/photo-1611312449408-fcece27cdbb7?w=700&q=85',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Cream', 'Charcoal', 'Navy', 'Brown'],
    rating: 4.8,
    reviewCount: 312,
    soldCount: 740,
    isFeatured: true,
    rackId: 'rack_men_casual',
    rackName: "Men's Casual",
    details: {
      'Material': '100% Merino Wool',
      'Fit': 'Relaxed',
      'Pattern': 'Cable Knit',
      'Care': 'Hand Wash Cold'
    },
  ),
  const Product(
    id: 'p06',
    name: 'Classic Cardigan',
    brand: 'Ralph Lauren',
    description:
        'An enduring wardrobe staple. Ribbed collar and cuffs, button front closure. Crafted from a soft wool blend for all-day comfort.',
    price: 29997.0,
    originalPrice: 42000.0,
    category: 'Men',
    subCategory: 'Casual',
    images: [
      'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=700&q=85',
      'https://images.unsplash.com/photo-1611312449408-fcece27cdbb7?w=700&q=85',
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Brown', 'Black', 'Navy'],
    rating: 4.5,
    reviewCount: 178,
    soldCount: 510,
    isFeatured: true,
    rackId: 'rack_men_casual',
    rackName: "Men's Casual",
    details: {
      'Material': 'Wool Blend',
      'Buttons': 'Horn',
      'Collar': 'Ribbed',
      'Care': 'Dry Clean Preferred'
    },
  ),
  const Product(
    id: 'p07',
    name: 'Linen Overshirt',
    brand: 'Tommy Hilfiger',
    description:
        'Relaxed linen overshirt — wear it open over a tee or buttoned as a light layer. Stone-washed for a naturally worn-in feel.',
    price: 22497.0,
    originalPrice: 29400.0,
    category: 'Men',
    subCategory: 'Casual',
    images: [
      'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=700&q=85',
      'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=700&q=85',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Stone', 'Sage', 'White'],
    rating: 4.4,
    reviewCount: 245,
    soldCount: 680,
    isNew: true,
    rackId: 'rack_men_casual',
    rackName: "Men's Casual",
    details: {
      'Material': '100% Linen',
      'Fit': 'Relaxed',
      'Treatment': 'Stone Washed',
      'Care': 'Machine Wash'
    },
  ),
  // ── Men's Streetwear ──────────────────────────────────────
  const Product(
    id: 'p08',
    name: 'Oversized Hoodie',
    brand: 'Chanel',
    description:
        'The definitive streetwear staple. Heavyweight 400gsm fleece, kangaroo pocket, ribbed cuffs. An oversized silhouette engineered for maximum comfort and effortless style.',
    price: 35997.0,
    originalPrice: 48000.0,
    category: 'Men',
    subCategory: 'Streetwear',
    images: [
      'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=700&q=85',
      'https://images.unsplash.com/photo-1542338347-4fff3276af78?w=700&q=85',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Cream', 'Charcoal'],
    rating: 4.8,
    reviewCount: 792,
    soldCount: 2100,
    isNew: true,
    isFeatured: true,
    rackId: 'rack_streetwear',
    rackName: 'Streetwear',
    details: {
      'Material': '400gsm Fleece',
      'Fit': 'Oversized',
      'Weight': 'Heavyweight',
      'Care': 'Machine Wash Cold'
    },
  ),
  const Product(
    id: 'p09',
    name: 'Cargo Tech Pants',
    brand: 'Versace',
    description:
        'Technical cargo pants where function meets fashion. Multiple zip pockets, adjustable waistband, tapered leg silhouette. Water-resistant ripstop nylon.',
    price: 44997.0,
    originalPrice: 60000.0,
    category: 'Men',
    subCategory: 'Streetwear',
    images: [
      'https://images.unsplash.com/photo-1542272604-787c3835535d?w=700&q=85',
      'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=700&q=85',
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'Khaki', 'Olive'],
    rating: 4.6,
    reviewCount: 234,
    soldCount: 560,
    rackId: 'rack_streetwear',
    rackName: 'Streetwear',
    details: {
      'Material': 'Ripstop Nylon',
      'Pockets': '6 Zip',
      'Feature': 'Water Resistant',
      'Care': 'Machine Wash'
    },
  ),
  // ── Women's Casual ────────────────────────────────────────
  const Product(
    id: 'p10',
    name: 'Floral Midi Dress',
    brand: 'Gucci',
    description:
        'Effortlessly feminine floral midi dress. V-neckline, flowing silhouette, adjustable tie waist. Crafted from lightweight viscose for all-day ease.',
    price: 38997.0,
    originalPrice: 54000.0,
    category: 'Women',
    subCategory: 'Casual',
    images: [
      'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=700&q=85',
      'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=700&q=85',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Floral Blue', 'Floral Pink'],
    rating: 4.8,
    reviewCount: 567,
    soldCount: 1340,
    isNew: true,
    isFeatured: true,
    rackId: 'rack_women_casual',
    rackName: "Women's Casual",
    details: {
      'Material': '100% Viscose',
      'Fit': 'Relaxed',
      'Length': 'Midi',
      'Care': 'Hand Wash'
    },
  ),
  const Product(
    id: 'p11',
    name: 'High-Waist Wide Leg Jeans',
    brand: 'Calvin Klein',
    description:
        'A modern take on the wide-leg silhouette. Premium stretch denim, high-rise waist that flatters every body type. Finished with subtle hardware.',
    price: 32997.0,
    category: 'Women',
    subCategory: 'Casual',
    images: [
      'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=700&q=85',
      'https://images.unsplash.com/photo-1475178626620-a4d074967452?w=700&q=85',
    ],
    sizes: ['24', '25', '26', '27', '28', '30'],
    colors: ['Light Wash', 'Dark Wash', 'Black'],
    rating: 4.7,
    reviewCount: 883,
    soldCount: 2500,
    rackId: 'rack_women_casual',
    rackName: "Women's Casual",
    details: {
      'Material': '93% Cotton, 7% Elastane',
      'Rise': 'High',
      'Fit': 'Wide Leg',
      'Care': 'Machine Wash'
    },
  ),
  const Product(
    id: 'p12',
    name: 'Oversized Knit Sweater',
    brand: 'Dior',
    description:
        'A luxuriously cozy chunky-knit pullover in an 80/20 wool-cashmere blend. Dropped shoulders with refined ribbed trims. The ultimate statement in soft, seasonal dressing.',
    price: 32997.0,
    originalPrice: 46500.0,
    category: 'Women',
    subCategory: 'Casual',
    images: [
      'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=700&q=85',
      'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=700&q=85',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Cream', 'Dusty Rose', 'Sage'],
    rating: 4.8,
    reviewCount: 523,
    soldCount: 1290,
    isNew: true,
    isFeatured: true,
    rackId: 'rack_women_casual',
    rackName: "Women's Casual",
    details: {
      'Material': '80% Wool, 20% Cashmere',
      'Fit': 'Oversized',
      'Pattern': 'Chunky Knit',
      'Care': 'Hand Wash Cold'
    },
  ),
  const Product(
    id: 'p13',
    name: 'Summer Linen Blouse',
    brand: 'Tommy Hilfiger',
    description:
        'Breezy linen blouse with subtle pintuck detailing and a relaxed drape. Perfect over jeans or tucked into a midi skirt.',
    price: 19497.0,
    originalPrice: 26700.0,
    category: 'Women',
    subCategory: 'Casual',
    images: [
      'https://images.unsplash.com/photo-1485968579580-b6d095142e6e?w=700&q=85',
      'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=700&q=85',
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['White', 'Ecru', 'Dusty Blue'],
    rating: 4.5,
    reviewCount: 302,
    soldCount: 870,
    isNew: true,
    rackId: 'rack_women_casual',
    rackName: "Women's Casual",
    details: {
      'Material': '100% Linen',
      'Fit': 'Relaxed',
      'Detail': 'Pintuck',
      'Care': 'Machine Wash Cold'
    },
  ),
  // ── Women's Formal ────────────────────────────────────────
  const Product(
    id: 'p14',
    name: 'Tailored Blazer Dress',
    brand: 'Prada',
    description:
        'A power-dressing icon. Italian crepe, peak lapels, a defined waist, and single-button closure. Commands attention in every room.',
    price: 65997.0,
    originalPrice: 96000.0,
    category: 'Women',
    subCategory: 'Formal',
    images: [
      'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=700&q=85',
      'https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=700&q=85',
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Black', 'Ivory', 'Deep Red'],
    rating: 4.9,
    reviewCount: 189,
    soldCount: 380,
    isFeatured: true,
    rackId: 'rack_women_formal',
    rackName: "Women's Formal",
    details: {
      'Material': 'Italian Crepe',
      'Fit': 'Tailored',
      'Closure': 'Single Button',
      'Care': 'Dry Clean'
    },
  ),
  const Product(
    id: 'p15',
    name: 'Satin Slip Dress',
    brand: 'Gucci',
    description:
        'Effortlessly chic bias-cut satin slip dress. Adjustable spaghetti straps, subtle sheen, fluid drape. A modern classic for evenings out.',
    price: 29997.0,
    originalPrice: 45000.0,
    category: 'Women',
    subCategory: 'Formal',
    images: [
      'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=700&q=85',
      'https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=700&q=85',
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Champagne', 'Dusty Rose', 'Black'],
    rating: 4.7,
    reviewCount: 456,
    soldCount: 980,
    rackId: 'rack_women_formal',
    rackName: "Women's Formal",
    details: {
      'Material': '100% Satin',
      'Fit': 'Bias Cut',
      'Straps': 'Adjustable',
      'Care': 'Hand Wash Cold'
    },
  ),
  const Product(
    id: 'p16',
    name: 'Structured Midi Skirt',
    brand: 'Chanel',
    description:
        'A polished pencil midi skirt with a back kick pleat for ease of movement. Crafted from a luxe ponte fabric that holds its shape beautifully.',
    price: 26997.0,
    originalPrice: 39000.0,
    category: 'Women',
    subCategory: 'Formal',
    images: [
      'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=700&q=85',
      'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=700&q=85',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Black', 'Navy', 'Ivory'],
    rating: 4.6,
    reviewCount: 223,
    soldCount: 610,
    rackId: 'rack_women_formal',
    rackName: "Women's Formal",
    details: {
      'Material': 'Ponte Knit',
      'Fit': 'Fitted',
      'Length': 'Midi',
      'Care': 'Dry Clean Preferred'
    },
  ),
  // ── Women's Streetwear ────────────────────────────────────
  const Product(
    id: 'p17',
    name: 'Cropped Leather Jacket',
    brand: 'Versace',
    description:
        'The definitive statement piece. Premium vegan leather, silver-tone hardware, asymmetric zip closure. Pairs with everything from slip dresses to wide-leg jeans.',
    price: 89997.0,
    originalPrice: 135000.0,
    category: 'Women',
    subCategory: 'Streetwear',
    images: [
      'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=700&q=85',
      'https://images.unsplash.com/photo-1548624313-0396c75e4b1a?w=700&q=85',
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Black', 'Burgundy', 'Tan'],
    rating: 4.9,
    reviewCount: 342,
    soldCount: 710,
    isNew: true,
    isFeatured: true,
    rackId: 'rack_streetwear',
    rackName: 'Streetwear',
    details: {
      'Material': 'Vegan Leather',
      'Fit': 'Cropped',
      'Hardware': 'Silver',
      'Care': 'Wipe Clean'
    },
  ),
  const Product(
    id: 'p18',
    name: 'White Leather Sneakers',
    brand: 'Versace',
    description:
        'Minimalist white leather sneakers with a cushioned memory-foam insole. Clean lines, signature back-tab, rubber outsole. Effortlessly versatile.',
    price: 38997.0,
    category: 'Women',
    subCategory: 'Streetwear',
    images: [
      'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=700&q=85',
      'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=700&q=85',
    ],
    sizes: ['36', '37', '38', '39', '40', '41'],
    colors: ['White', 'Black'],
    rating: 4.9,
    reviewCount: 678,
    soldCount: 2300,
    isFeatured: true,
    rackId: 'rack_streetwear',
    rackName: 'Streetwear',
    details: {
      'Material': 'Premium Leather',
      'Sole': 'Rubber',
      'Insole': 'Memory Foam',
      'Care': 'Wipe Clean'
    },
  ),
  // ── Kids ──────────────────────────────────────────────────
  const Product(
    id: 'p19',
    name: 'Denim Overalls',
    brand: 'Tommy Hilfiger',
    description:
        'Durable and adorable denim overalls with adjustable straps and reinforced knees. Built to keep up with every adventure.',
    price: 14997.0,
    originalPrice: 21000.0,
    category: 'Kids',
    subCategory: 'Casual',
    images: [
      'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=700&q=85',
      'https://images.unsplash.com/photo-1471286174890-9c112ffca5b4?w=700&q=85',
    ],
    sizes: ['3T', '4T', '5T', '6', '7', '8'],
    colors: ['Light Denim', 'Dark Denim'],
    rating: 4.8,
    reviewCount: 234,
    soldCount: 670,
    rackId: 'rack_kids',
    rackName: "Kids' Section",
    details: {
      'Material': 'Soft Denim',
      'Feature': 'Reinforced Knees',
      'Straps': 'Adjustable',
      'Care': 'Machine Wash'
    },
  ),
  const Product(
    id: 'p20',
    name: 'Graphic Tee & Shorts Set',
    brand: 'Ralph Lauren',
    description:
        'Fun graphic tee and matching pull-on shorts. Super-soft 100% cotton jersey. The perfect play set.',
    price: 11997.0,
    category: 'Kids',
    subCategory: 'Casual',
    images: [
      'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=700&q=85',
      'https://images.unsplash.com/photo-1471286174890-9c112ffca5b4?w=700&q=85',
    ],
    sizes: ['3T', '4T', '5T', '6', '7', '8'],
    colors: ['Blue', 'Red', 'Yellow'],
    rating: 4.6,
    reviewCount: 178,
    soldCount: 440,
    isNew: true,
    rackId: 'rack_kids',
    rackName: "Kids' Section",
    details: {
      'Material': '100% Cotton',
      'Set': '2-Piece',
      'Waistband': 'Elastic',
      'Care': 'Machine Wash'
    },
  ),
  // ── Accessories ───────────────────────────────────────────
  const Product(
    id: 'p21',
    name: 'Full-Grain Leather Tote',
    brand: 'Chanel',
    description:
        'Spacious, elegant tote in full-grain vegetable-tanned leather. Gold-tone hardware, interior zip pocket, cotton canvas lining. Improves with age.',
    price: 56997.0,
    originalPrice: 84000.0,
    category: 'Accessories',
    subCategory: 'Bags',
    images: [
      'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=700&q=85',
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=700&q=85',
    ],
    sizes: ['One Size'],
    colors: ['Tan', 'Black', 'Cognac'],
    rating: 4.9,
    reviewCount: 312,
    soldCount: 540,
    isFeatured: true,
    rackId: 'rack_accessories',
    rackName: 'Accessories',
    details: {
      'Material': 'Full-Grain Leather',
      'Hardware': 'Gold-Tone',
      'Dimensions': '14x12x5"',
      'Lining': 'Canvas'
    },
  ),
  const Product(
    id: 'p22',
    name: 'Merino Wool Scarf',
    brand: 'Prada',
    description:
        'Luxuriously soft merino wool scarf in a classic ribbed pattern. Extra-long for versatile styling — wrap, drape, or layer.',
    price: 20997.0,
    originalPrice: 30000.0,
    category: 'Accessories',
    subCategory: 'Scarves',
    images: [
      'https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=700&q=85',
      'https://images.unsplash.com/photo-1574180566232-aaad1b5b8450?w=700&q=85',
    ],
    sizes: ['One Size'],
    colors: ['Camel', 'Charcoal', 'Cream', 'Burgundy'],
    rating: 4.8,
    reviewCount: 145,
    soldCount: 320,
    rackId: 'rack_accessories',
    rackName: 'Accessories',
    details: {
      'Material': '100% Merino Wool',
      'Length': '180cm',
      'Pattern': 'Ribbed Knit',
      'Care': 'Hand Wash'
    },
  ),
  const Product(
    id: 'p23',
    name: 'Minimalist Leather Watch',
    brand: 'Dior',
    description:
        'Swiss-movement timepiece with a brushed stainless case, sapphire crystal, and genuine leather strap. Understated luxury for the discerning wearer.',
    price: 89997.0,
    originalPrice: 126000.0,
    category: 'Accessories',
    subCategory: 'Watches',
    images: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=700&q=85',
      'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=700&q=85',
    ],
    sizes: ['One Size'],
    colors: ['Black', 'Brown'],
    rating: 4.9,
    reviewCount: 198,
    soldCount: 290,
    isFeatured: true,
    rackId: 'rack_accessories',
    rackName: 'Accessories',
    details: {
      'Case': '38mm Stainless',
      'Crystal': 'Sapphire',
      'Movement': 'Swiss Quartz',
      'Strap': 'Genuine Leather'
    },
  ),
  const Product(
    id: 'p24',
    name: 'Polarized Sunglasses',
    brand: 'Gucci',
    description:
        'Sleek geometric frames with polarized UV400 lenses. Lightweight acetate, spring hinges. Effortless cool with all-day comfort.',
    price: 44997.0,
    originalPrice: 63000.0,
    category: 'Accessories',
    subCategory: 'Eyewear',
    images: [
      'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=700&q=85',
      'https://images.unsplash.com/photo-1508296695146-257a814070b4?w=700&q=85',
    ],
    sizes: ['One Size'],
    colors: ['Black', 'Tortoise', 'Gold'],
    rating: 4.7,
    reviewCount: 267,
    soldCount: 430,
    rackId: 'rack_accessories',
    rackName: 'Accessories',
    details: {
      'Frame': 'Lightweight Acetate',
      'Lens': 'Polarized UV400',
      'Hinges': 'Spring',
      'Fit': 'Medium'
    },
  ),
  const Product(
    id: 'p25',
    name: 'Woven Leather Belt',
    brand: 'Prada',
    description:
        'Hand-woven full-grain leather belt with a matte silver buckle. A masterclass in Italian craftsmanship. Fits waist 28–40".',
    price: 23997.0,
    originalPrice: 34500.0,
    category: 'Accessories',
    subCategory: 'Belts',
    images: [
      'https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=700&q=85',
      'https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=700&q=85',
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'Tan', 'Brown'],
    rating: 4.6,
    reviewCount: 134,
    soldCount: 280,
    rackId: 'rack_accessories',
    rackName: 'Accessories',
    details: {
      'Material': 'Full-Grain Leather',
      'Buckle': 'Matte Silver',
      'Width': '3.5cm',
      'Origin': 'Italy'
    },
  ),
  const Product(
    id: 'p26',
    name: 'Canvas Baseball Cap',
    brand: 'Ralph Lauren',
    description:
        'Six-panel unstructured cap in premium canvas. Embroidered tonal logo, curved brim, adjustable back strap. The finishing touch.',
    price: 13497.0,
    category: 'Accessories',
    subCategory: 'Hats',
    images: [
      'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=700&q=85',
      'https://images.unsplash.com/photo-1556306535-0f09a537f0a3?w=700&q=85',
    ],
    sizes: ['One Size'],
    colors: ['Black', 'Cream', 'Navy', 'Olive'],
    rating: 4.5,
    reviewCount: 289,
    soldCount: 760,
    isNew: true,
    rackId: 'rack_accessories',
    rackName: 'Accessories',
    details: {
      'Material': 'Canvas',
      'Closure': 'Adjustable',
      'Panels': '6',
      'Care': 'Spot Clean'
    },
  ),
  const Product(
    id: 'p27',
    name: 'High-Top Leather Boots',
    brand: 'Versace',
    description:
        'Italian-crafted high-top boots in supple full-grain leather. Cushioned footbed, lug sole, YKK side zip for easy on-off. Built to last a decade.',
    price: 104997.0,
    originalPrice: 144000.0,
    category: 'Accessories',
    subCategory: 'Shoes',
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=700&q=85',
      'https://images.unsplash.com/photo-1600269452121-4f2416e55c28?w=700&q=85',
    ],
    sizes: ['39', '40', '41', '42', '43', '44', '45'],
    colors: ['Black', 'Dark Brown'],
    rating: 4.8,
    reviewCount: 156,
    soldCount: 210,
    isFeatured: true,
    rackId: 'rack_accessories',
    rackName: 'Accessories',
    details: {
      'Material': 'Full-Grain Leather',
      'Sole': 'Lug',
      'Closure': 'Side Zip + Laces',
      'Origin': 'Italy'
    },
  ),
  const Product(
    id: 'p28',
    name: 'Structured Crossbody Bag',
    brand: 'Chanel',
    description:
        'Compact yet capacious structured crossbody in pebbled leather. Adjustable chain strap, magnetic snap closure, suede-lined interior.',
    price: 65997.0,
    originalPrice: 93000.0,
    category: 'Accessories',
    subCategory: 'Bags',
    images: [
      'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=700&q=85',
      'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=700&q=85',
    ],
    sizes: ['One Size'],
    colors: ['Black', 'Dusty Rose', 'Tan'],
    rating: 4.9,
    reviewCount: 278,
    soldCount: 390,
    isNew: true,
    rackId: 'rack_accessories',
    rackName: 'Accessories',
    details: {
      'Material': 'Pebbled Leather',
      'Strap': 'Chain (Adjustable)',
      'Closure': 'Magnetic Snap',
      'Lining': 'Suede'
    },
  ),
];

final kBanners = <BannerData>[
  const BannerData(
    id: 'b1',
    imageUrl:
        'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=900&q=85',
    title: 'New Season\nEditorial',
    subtitle: 'Curated looks for the season ahead',
    actionLabel: 'Explore Now',
    route: '/explore',
    tag: 'SS 2025',
  ),
  const BannerData(
    id: 'b2',
    imageUrl:
        'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=900&q=85',
    title: "Women's\nEssentials",
    subtitle: 'Timeless pieces, refined for today',
    actionLabel: 'Discover',
    route: '/explore',
    tag: 'NEW IN',
  ),
  const BannerData(
    id: 'b3',
    imageUrl:
        'https://images.unsplash.com/photo-1445205170230-053b83016050?w=900&q=85',
    title: 'Up to 35%\nOff',
    subtitle: 'End of season sale — limited time',
    actionLabel: 'Shop Sale',
    route: '/explore',
    tag: 'SALE',
  ),
  const BannerData(
    id: 'b4',
    imageUrl:
        'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=900&q=85',
    title: 'Accessories\nEdit',
    subtitle: 'Complete your look with the right detail',
    actionLabel: 'Browse',
    route: '/explore',
    tag: 'EDIT',
  ),
];

final kCategories = <CategoryData>[
  const CategoryData(
    id: 'men',
    name: 'Men',
    emoji: '👔',
    imageUrl:
        'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=400&q=80',
  ),
  const CategoryData(
    id: 'women',
    name: 'Women',
    emoji: '👗',
    imageUrl:
        'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=400&q=80',
  ),
  const CategoryData(
    id: 'kids',
    name: 'Kids',
    emoji: '🎒',
    imageUrl:
        'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=400&q=80',
  ),
  const CategoryData(
    id: 'accessories',
    name: 'Accessories',
    emoji: '👜',
    imageUrl:
        'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=400&q=80',
  ),
];

const kRackMap = <String, List<String>>{
  'rack_men_formal': ['p01', 'p02', 'p03'],
  'rack_men_casual': ['p04', 'p05', 'p06', 'p07'],
  'rack_streetwear': ['p08', 'p09', 'p17', 'p18'],
  'rack_women_casual': ['p10', 'p11', 'p12', 'p13'],
  'rack_women_formal': ['p14', 'p15', 'p16'],
  'rack_kids': ['p19', 'p20'],
  'rack_accessories': ['p21', 'p22', 'p23', 'p24', 'p25', 'p26', 'p27', 'p28'],
};

const kRackNames = <String, String>{
  'rack_men_formal': "Men's Formal Section",
  'rack_men_casual': "Men's Casual Section",
  'rack_streetwear': 'Streetwear Collection',
  'rack_women_casual': "Women's Casual Section",
  'rack_women_formal': "Women's Formal Section",
  'rack_kids': "Kids' Section",
  'rack_accessories': 'Accessories',
};

const colorMap = <String, Color>{
  'White': Color(0xFFF8F8F8),
  'Black': Color(0xFF1A1A1A),
  'Light Blue': Color(0xFF64B5F6),
  'Navy': Color(0xFF0D47A1),
  'Charcoal': Color(0xFF424242),
  'Khaki': Color(0xFFC8AD7F),
  'Olive': Color(0xFF6B8E23),
  'Brown': Color(0xFF6B3F2A),
  'Cream': Color(0xFFFFF8DC),
  'Stone': Color(0xFFD4C5B0),
  'Sage': Color(0xFFB2C5B0),
  'Ecru': Color(0xFFF5F0E8),
  'Floral Blue': Color(0xFF6495ED),
  'Floral Pink': Color(0xFFF8A4B8),
  'Ivory': Color(0xFFFFFFF0),
  'Deep Red': Color(0xFFB71C1C),
  'Light Wash': Color(0xFFB3C7E6),
  'Dark Wash': Color(0xFF3A5A8C),
  'Light Denim': Color(0xFF7BA3D4),
  'Dark Denim': Color(0xFF3B5998),
  'Tan': Color(0xFFD2B48C),
  'Champagne': Color(0xFFF7E7CE),
  'Dusty Rose': Color(0xFFDCB2A8),
  'Dusty Blue': Color(0xFF9DB4C0),
  'Red': Color(0xFFE53935),
  'Yellow': Color(0xFFFFEB3B),
  'Blue': Color(0xFF2962FF),
  'Camel': Color(0xFFC19A6B),
  'Cognac': Color(0xFF9A463D),
  'Grey': Color(0xFF9E9E9E),
  'Burgundy': Color(0xFF800020),
  'Gold': Color(0xFFC4A265),
  'Tortoise': Color(0xFF8B5E3C),
  'Dark Brown': Color(0xFF4A2C0A),
};
